---
title: "DGE analysis of mPFC"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2020-10-06 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: show
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries required

```{r, message=FALSE, warning=FALSE}
library(limma)
library(edgeR)
library(plgINS)
library(sva)
library(ggplot2)
library(dplyr)
library(patchwork)
library(SummarizedExperiment)
library(reshape2)
library(autoplotly)
library(pheatmap)
library(viridis)
library(RColorBrewer)
library(ggplotify)
```

# Load salmon object
```{r, message=FALSE, warning=FALSE}
load("input/mPFC_rnaseq_salmon.tds.RData")
```

# Differeitial analysis using `limma`

## All samples
```{r }
design <- model.matrix(~ 0 + Group, data = salmon@phenoData)
colnames(design) <- gsub(pattern = "Group", replacement = "", x = colnames(design))

y <- DGEList(counts = salmon@gene.counts)
keep <- filterByExpr(y, design, min.count = 20)
y <- y[keep, ]

dds <- calcNormFactors(y)
v <- voom(dds, design = design)

contrast.matrix <- makeContrasts(MSUS - CTRL, levels = design)
fit <- lmFit(v)

fit2 <- contrasts.fit(fit, contrast.matrix)
fit2 <- eBayes(fit2)

dea <- as.data.frame(topTable(fit2, coef = 1, number = Inf))
dea <- data.frame(Genes = rownames(dea), dea, stringsAsFactors = F)
dea_sig <- dea[abs(dea$logFC) >= 1 & dea$adj.P.Val <= 0.05, ]
```


## Removing L001
```{r }
design_l1 <- model.matrix(~ 0 + Group, data = salmon@phenoData[-1,])
colnames(design_l1) <- gsub(pattern = "Group", replacement = "", x = colnames(design_l1))

y_l1 <- DGEList(counts = salmon@gene.counts[,-1])
keep_l1 <- filterByExpr(y_l1, design_l1, min.count = 20)
y_l1 <- y_l1[keep_l1, ]

dds_l1 <- calcNormFactors(y_l1)
v_l1 <- voom(dds_l1, design = design_l1)

contrast.matrix_l1 <- makeContrasts(MSUS - CTRL, levels = design_l1)
fit_l1 <- lmFit(v_l1)

fit2_l1 <- contrasts.fit(fit_l1, contrast.matrix_l1)
fit2_l1 <- eBayes(fit2_l1)

dea_l1 <- as.data.frame(topTable(fit2_l1, coef = 1, number = Inf))
dea_l1 <- data.frame(Genes = rownames(dea_l1), dea_l1, stringsAsFactors = F)
dea_sig_l1 <- dea_l1[abs(dea_l1$logFC) >= 1 & dea_l1$adj.P.Val <= 0.05, ]
```



# `cpm` Counts data and pData

```{r }
y <- DGEList(counts = salmon@gene.counts)
dds <- calcNormFactors(y)
cpm <- cpm(dds, log = T)

data <- list(cpm = cpm, pData = salmon@phenoData)

save(data,
  file = "./output/data_pData.RData", compress = T,
  compression_level = 3
)
```

# Results
```{r }
dea.list <- list(`CTRL vs MSUS` = as.DEA(dea),
                 `CTRL vs MSUS (no L001)` = as.DEA(dea_l1))

normCounts <- v$E

voomEList <- v

dea.limma <- list(`CTRL vs MSUS` = dea)
```


## Save RData files
```{r }
save(dea.list,
  file = "./output/dea_mPFC_lit.DEA.RData", compress = T,
  compression_level = 3
)

save(normCounts,
  file = "./output/normCounts_voom_mPFC_lit.RData", compress = T,
  compression_level = 3
)

save(voomEList,
  file = "./output/voom_EList_mPFC_lit.RData", compress = T,
  compression_level = 3
)

save(dea,
  file = "./output/limma_mPFC_lit.RData", compress = T,
  compression_level = 3
)

writexl::write_xlsx(x = dea, path = "output/dea_results.xlsx", col_names = T, format_headers = T)
```


# MA plots

## All samples
```{r }
res <- dea
res$threshold <- as.factor(res$adj.P.Val < 0.1)

p1 <- ggplot(data = res, aes(
  x = res$AveExpr,
  y = res$logFC,
  colour = threshold
)) +
  geom_point(alpha = 0.5, size = 1.8) +
  geom_hline(aes(yintercept = 0), colour = "blue", size = 1) +
  ylim(c(
    -ceiling(max(abs(res$logFC))),
    ceiling(max(abs(res$logFC)))
  )) +
  ggtitle("MSUS vs CTRL") +
  labs(subtitle = "loess fit") +
  xlab("Mean expression") +
  ylab("Log2 Fold Change") +
  theme_bw() +
  theme(
    plot.title = element_text(face = "bold", size = 20, hjust = 0.5),
    plot.subtitle = element_text(size = 16, hjust = 0.5, face = "italic", color = "blue"),
    axis.title = element_text(face = "bold", size = 15),
    axis.text = element_text(face = "bold", size = 12),
    legend.title = element_text(face = "bold", size = 15),
    legend.text = element_text(size = 14),
    panel.border = element_rect(colour = "black", fill=NA, size=2)
  ) +
  scale_color_manual(name = "p.adjusted < 0.1", values=brewer.pal(n = 3, name = "Set1")[1:2])+ NULL
  stat_smooth(se = FALSE, method = "loess", color = "red", formula = y ~ x, size = 1)
```

## Removing L0001
```{r }
res_l1 <- dea_l1
res_l1$threshold <- as.factor(res_l1$adj.P.Val < 0.1)

p2 <- ggplot(data = res_l1, aes(
  x = res_l1$AveExpr,
  y = res_l1$logFC,
  colour = threshold
)) +
  geom_point(alpha = 0.8, size = 3) +
  geom_hline(aes(yintercept = 0), colour = "blue", size = 1) +
  ylim(c(
    -ceiling(max(abs(res_l1$logFC))),
    ceiling(max(abs(res_l1$logFC)))
  )) +
  ggtitle("MSUS vs CTRL (no L1)") +
  labs(subtitle = "loess fit") +
  xlab("Mean expression") +
  ylab("Log2 Fold Change") +
  theme_bw() +
  theme(
    plot.title = element_text(face = "bold", size = 20, hjust = 0.5),
    plot.subtitle = element_text(size = 16, hjust = 0.5, face = "italic", color = "blue"),
    axis.title = element_text(face = "bold", size = 15),
    axis.text = element_text(face = "bold", size = 12),
    legend.title = element_text(face = "bold", size = 15),
    legend.text = element_text(size = 14),
    panel.border = element_rect(colour = "black", fill=NA, size=2)
  ) +
  scale_color_manual(name = "p.adjusted < 0.1", values=brewer.pal(n = 3, name = "Set1")[1:2])+ NULL
  stat_smooth(se = FALSE, method = "loess", color = "red", formula = y ~ x, size = 1)
```


```{r, fig.height=5, fig.width=11}
p1 | p2
```


# Heatmap of most variable genes

## All samples
```{r}
xvar <- apply((data$cpm + 1), 1, var)
genes500 <- head(sort(xvar, decreasing = TRUE), n = 500)
x500 <- data$cpm[rownames(data$cpm) %in% names(genes500), ]

pheatmap(x500, scale = "row", show_rownames = F, col = viridis(100), show_colnames = F, annotation_col = data$pData[,2:3], main = "Clustering of samples based on top 500 variable genes")
```

## Removing L001
```{r}
xvar <- apply((data$cpm[,-1] + 1), 1, var)
genes500 <- head(sort(xvar, decreasing = TRUE), n = 500)
x500 <- data$cpm[rownames(data$cpm) %in% names(genes500), ]

pheatmap(x500, scale = "row", show_rownames = F, col = viridis(100), show_colnames = F, annotation_col = data$pData[,2:3], main = "Clustering of samples based on top 500 variable genes (no L1)")
```


# PCA

## All samples
```{r, fig.height=8.5, fig.width=11}
pca <- prcomp(t(data$cpm))
# ggplotly(
  pc1 <- autoplot(pca,
  data = data$pData, colour = "Group",
  frame = TRUE, frame.type = "norm", size = 5
) +
  ggtitle("") + 
    theme_bw() +
    scale_color_manual(values=brewer.pal(n = 3, name = "Set1")[1:2]) +
    theme(axis.text.x = element_text(size = 20, colour = "black"),
        axis.text.y = element_text(size = 20, colour = "black"),  
        axis.title.x = element_text(size = 20, colour = "black"),
        axis.title.y = element_text(size = 20, colour = "black"),
        plot.title = element_text(size = 25, face = "bold", colour = "black"),
        legend.text=element_text(size=20, colour = "black"),
        legend.title=element_text(size=20, face = "bold"),
        panel.border = element_rect(colour = "black", fill=NA, size=2))
    
  
  pc2 <- autoplot(pca,
  data = data$pData, colour = "Lane",
  frame = TRUE, frame.type = "norm", size = 5
) +
  ggtitle("") + 
    theme_bw()+
    scale_color_manual(values=brewer.pal(n = 3, name = "Set1")[1:2]) +
    theme(axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),  
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 25, face = "bold"),
        legend.text=element_text(size=20),
        legend.title=element_text(size=20, face = "bold"),
        panel.border = element_rect(colour = "black", fill=NA, size=2))
  
  
  pca1 <- prcomp(t(data$cpm[,-1]))
# ggplotly(
  pc3 <- autoplot(pca1,
  data = data$pData[-1,], colour = "Group",
  frame = TRUE, frame.type = "norm", size = 5
) +
  ggtitle("") + 
    theme_bw() +
    scale_color_manual(values=brewer.pal(n = 3, name = "Set1")[1:2]) +
    theme(axis.text.x = element_text(size = 20, colour = "black"),
        axis.text.y = element_text(size = 20, colour = "black"),  
        axis.title.x = element_text(size = 20, colour = "black"),
        axis.title.y = element_text(size = 20, colour = "black"),
        plot.title = element_text(size = 25, face = "bold", colour = "black"),
        legend.text=element_text(size=20, colour = "black"),
        legend.title=element_text(size=20, face = "bold"),
        panel.border = element_rect(colour = "black", fill=NA, size=2))
    
```

```{r, fig.height=6, fig.width=11}
pc1|pc2
```

```{r, fig.height=7, fig.width=8}
pc3
```

## All samples
```{r}
pca1 <- plgINS::plPCA(x = data$cpm, samples_data = data$pData, colorBy = "Group", points.size = 20)
```

## Remove L1
```{r}
pca2 <- plgINS::plPCA(x = data$cpm[,-1], samples_data = data$pData[-1,], colorBy = "Group", points.size = 20)
```

### Fig
```{r, fig.height=5, fig.width=11}
subplot(pca1, pca2)
```



# References
```{r }
report::cite_packages(session = sessionInfo())
```


# SessionInfo
```{r }
devtools::session_info() %>%
  details::details()
```
