##############################
## @Author : Deepak Tanwar  ##
## @Date :   20201006       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("DGE_analysis.Rmd")' 2> log >> log
